### ISSUE TITLE
getReadableVersion is not implemented

### ISSUE THREAD

**Issue by adamkobor** [rvenky125/kmp-device-info#7]
**Describe the bug**
getReadableVersion is not implemented

**To Reproduce**
Try to invoke `DeviceInfo.getReadableVersion()`

**Expected behavior**
It should be available according to the docs.

**Comment by rvenky125** [comment]
Thanks for noticing that, I was off for some time, will actively start work on this lib.

**Comment by rvenky125** [comment]
Fix added in realease https://github.com/rvenky125/kmp-device-info/releases/tag/v0.0.20-alpha
